<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="coverlet.msbuild" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Terminal.Gui" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\..\src\Vela.Core\Vela.Core.csproj" />
    <ProjectReference Include="..\..\src\Vela.Windows\Vela.Windows.csproj" />
    <ProjectReference Include="..\..\src\Vela.Tui\Vela.Tui.csproj" />
    <ProjectReference Include="..\..\src\Vela.Application\Vela.Application.csproj" />
  </ItemGroup>

</Project>
